# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d31e7e3fbab8c874acda1e5eadd1778c6fae953a1f86e356930aee47124e5cbbcb7cf23bb7e640fb9c93eeb09d4dceda00490b4c515e130663f859806b287fc

test:
  secret_key_base: 1ff6433bcce470391bca6478b11826e6564d4f8a2876ca19200c831951a45dfacc022b484a28d770a77201caaacd31c42297e341ca095f84cfd71cc156ecd26d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
